executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"

jobs:
  Hello-stockOS:
    executor: node/default
    steps:
      - run:
          name: Hello stockOS
          command: |
            echo 'Hello stockOS'
