executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"

jobs:
  Hello-StockOS:
    executor: node/default
    steps:
      - run:
          name: Hello StockOS
          command: |
            echo 'Hello StockOS'
  Install-node-example:
    executor: my-executor
    steps:
      - checkout
      - node/install:
          install-npm: true
      - run: node --version
  Verify-eslint:
    executor: my-executor
    steps:
      - checkout
      - node/install:
          install-npm: true
      - node/install-packages:
          override-ci-command: npm install
      - run:
          command: |
            npm run eslint
  Test-mocha:
    executor: my-executor
    steps:
      - checkout
      - node/install:
          install-npm: true
      - node/install-packages:
          override-ci-command: npm install
      - run: node --version
      - run: echo AIzaSyBhnIoj7mVqH6fUSZMfpeS0vTqT6RTfXTA | base64 --decode > serviceAccountKey.json
      - run: cat serviceAccountKey.json
      - run: npm run test

orbs:
  node: circleci/node@4.0.1
version: 2.1
workflows:
  StockOS:
    jobs:
      - Hello-StockOS
      - Install-node-example
      - Verify-eslint
      - Test-mocha